### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by maxime1992** [brechtbilliet/ngxReactiveToolkit#19]
Hi,

I think there's no changelog on this project and upgrading with the following is scary without knowing the breaking change :) 
```
ngx-reactivetoolkit                latest  5.1.1         ❯  6.1.1 
```

**Comment by RubenVermeulen** [comment]
Hi @maxime1992 

You're totally right. We don't have any changelog available currently, we should though. I'll make sure we start doing this from now on.

As far as changes go, there isn't anything breaking except for the fact that we upgraded to Angular 8.

There is also a new feature that gives you the ability to pass along an initial value with the @Changes decorator. You can find an example in the README.

-- Ruben

**Comment by RubenVermeulen** [comment]
New version has been released accompanied with a changelog file.
