### ISSUE TITLE
@Changes('x') only supports single usage

### ISSUE THREAD

**Issue by tyroneneill** [brechtbilliet/ngxReactiveToolkit#29]
Hi, 

Thanks for the awesome library! 

I was recently using the @Changes decorator with named properties and noticed when I had multiple usages in a single instance the expected values are not being reflected. 

I reverted the code to the more traditional/manual/less reactive variation:

```
@Input() a:string;
private aUpdates = new BehaviourSubject(undefined);

public ngOnChanges( changes: SimpleChanges): void {
    if(changes.a) {
      this.aUpdates.next(changes.a.currentValue); 
    }
}
```
and all was good in the world again! 

Created a [simple reproduction](https://stackblitz.com/edit/angular-i3mhk8) of the issue and have had a little stab at the [solution](https://github.com/brechtbilliet/ngxReactiveToolkit/pull/28).

**Comment by RubenVermeulen** [comment]
@tyroneneill
Sorry for the late response. First of all thanks for reporting this issue. I'm currently debugging the issue, and will try and release a new version later this week.
